### ISSUE TITLE
SQL Connection Keeps Resetting

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/The-MMORPG-Project#23]
## Steps to Reproduce
1. Start web server.
2. Wait a while (15 to 30 minutes) (maybe more)
3. Try making a query through the web server to the database
4. Notice the error

## Hypothesis
Seems like the web server needs to keep in check the connection status of the MySQL connection and reconnect accordingly OR constantly disconnect and connect from the database for every query OR a combination of both.

## Error
```
(node:7308) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
    --------------------
    at Protocol._enqueue (C:\Users\valkyrienyanko\Desktop\ENet-Model\Web\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\valkyrienyanko\Desktop\ENet-Model\Web\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\valkyrienyanko\Desktop\ENet-Model\Web\node_modules\promise-mysql\lib\helper.js:26:45
    at Promise._execute (C:\Users\valkyrienyanko\Desktop\ENet-Model\Web\node_modules\bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\valkyrienyanko\Desktop\ENet-Model\Web\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\valkyrienyanko\Desktop\ENet-Model\Web\node_modules\bluebird\js\release\promise.js:103:10)
    at Connection.promiseCallback (C:\Users\valkyrienyanko\Desktop\ENet-Model\Web\node_modules\promise-mysq
```

**Comment by Shepardeon** [comment]
I gave a quick read and found this topic on stackoverflow: https://stackoverflow.com/questions/22900931/mysql-giving-read-econnreset-error-after-idle-time-on-node-js-server

Using a heartbeat to keep the connection alive seems to be a recommended solution by the node-sql module devs.

**Comment by valkyrienyanko** [comment]
@Shepardeon What's your Discord? I think I might have unfriended you by accident.

**Comment by valkyrienyanko** [comment]
Potential fix.

```ts
  //...
  setInterval(keepConnectionsAlive, 1000 * 10, db)
})()

function keepConnectionsAlive(db) 
{
  db.query("SELECT 1")
}
```

Will reopen issue if issue persists.
