### ISSUE TITLE
Console Buffer Overload

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/The-MMORPG-Project#4]
## Issue
Spamming a large amount of text covering more than 1 lines will eventually result in overloading the buffer height. The buffer height cannot keep up because it thinks you are always sending 1 lines worth of text even if you send 5 lines of text. The logger will only adjust the buffer height accordingly if you add `\n` to the end of each new line.

## Solution
The logger needs to somehow track how many lines were sent to the console adjust the buffer height accordingly. We may want to look at `Console.CursorTop` for this.

## Actual Error
```
Unhandled exception. System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 18.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Valk.Networking.Logger.Log(Object value) in C:\Users\valkyrienyanko\Desktop\ENet-Model\Server\Logger.cs:line 25
   at Valk.Networking.InputHandler.HandleCommands(String input) in C:\Users\valkyrienyanko\Desktop\ENet-Model\Server\InputHandler.cs:line 94
   at Valk.Networking.InputHandler.Run() in C:\Users\valkyrienyanko\Desktop\ENet-Model\Server\InputHandler.cs:line 71
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by valkyrienyanko** [comment]
https://stackoverflow.com/questions/849876/c-sharp-simultanous-console-input-and-output
